language: python

python:
  - 3.5

env:
  - TOX_ENV=py27-dj15
  - TOX_ENV=py27-dj16
  - TOX_ENV=py27-dj17
  - TOX_ENV=py27-dj18
  - TOX_ENV=py27-dj19
  - TOX_ENV=py34-dj15
  - TOX_ENV=py34-dj16
  - TOX_ENV=py34-dj17
  - TOX_ENV=py34-dj18
  - TOX_ENV=py34-dj19
  - TOX_ENV=py35-dj15
  - TOX_ENV=py35-dj16
  - TOX_ENV=py35-dj17
  - TOX_ENV=py35-dj18
  - TOX_ENV=lint
  - TOX_ENV=cover

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
